apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-dotnet
  labels:
    app: test-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dotnet
  template:
    metadata:
      labels:
        app: test-dotnet
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "test-dotnet"
    spec:
      containers:
      - name: test-dotnet
        image: xxx.azurecr.io/test-dotnet:latest
        imagePullPolicy: Always